server:
  port: 9003

spring:
  eureka:
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 20
    client:
      serviceUrl:
        defaultZone: http://smile:123456@111.230.46.97:9001/eureka
      registry-fetch-interval-seconds: 10
  boot:
    admin:
      turbine:
        location: yx-monitor
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream

turbine:
    app-config: yx-gateway #收集监控信息的服务名
    combine-host-port: true
    cluster-name-expression: new String('default') #集群名称

